### ISSUE TITLE
'assign' parsing extra text beyond question category

### ISSUE THREAD

**Issue by andrew-x-chen** [rishi-kulkarni/nsb-toolbox#23]
While running nsb assign:

`ValueError: 'Multiple Choice    ' is not a valid QuestionType`

Which occurs if the 4 spaces after 'Choice' are italicized. Fixed after de-italicizing those spaces.

`Have you run nsb format on it?`

However nsb format does not fix this issue at this time either.

**Comment by rishi-kulkarni** [comment]
I'm having trouble reproducing this one. Could you add a file that fails?

That is to say, I can see the line in `_base_questions.py` that would cause an error here, but format should left pad the stem with four non-italicized spaces.

**Comment by rishi-kulkarni** [comment]
Attaching the files here for posterity.
[testdoc2 - Copy.docx](https://github.com/rishi-kulkarni/nsb-toolbox/files/9805170/testdoc2.-.Copy.docx)
[testdoc3.docx](https://github.com/rishi-kulkarni/nsb-toolbox/files/9805172/testdoc3.docx)

From Andrew:

```
Ok so apparently I was mistaken, nsb format does actually fix whatever the problem is. 

However, the problem continues to be very strange, here is an example of a couple files that mess it up. When you do nsb format, it resolves whatever the issue is, without creating any change to the text of the file. (I did version compare between pre-format and post-format showing zero changes in between).

So anyway, it's not a priority issue given that nsb format fixes whatever it is. I assume it has to do with hidden xml elements that cause parsing the question type to over or underinclude things.
```

`nsb format` handles trailing whitespace issues and attempts to coerce all "weird" whitespaces (non-breaking spaces, non-breaking returns, etc.) to a single type (regular spaces and carriage returns). Closing this for now.
